=== RichardVinueza/U.T.4---Actividad-6---Proyecto-de-Github-con-Readme.md./tourism/public_html/country.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.richard.com/tourism"
           xmlns="https://www.richard.com/tourism"     
           elementFormDefault="qualified">
    
    <xs:element name="country">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="beaches"></xs:element>
                <xs:element ref="hotels"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="beaches">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="beach" minOccurs="1" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="hotels">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="hotel" minOccurs="1" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="beach">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="top"></xs:element>
                <xs:element ref="name"></xs:element>
                <xs:element ref="location"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="hotel">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name"></xs:element>
                <xs:element ref="place"></xs:element>
                <xs:element ref="price"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
     
    <xs:element name="top" type="position"></xs:element>
    <xs:element name="name" type="nameBeachHotel"></xs:element>
    <xs:element name="location" type="somewhere"></xs:element>
    <xs:element name="place" type="somewhere"></xs:element>
    <xs:element name="price" type="money"></xs:element>
    
    <xs:simpleType name="position">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{1}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="nameBeachHotel">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-z][a-z].+"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="somewhere">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-z][a-z].+"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="money">
        <xs:restriction base="xs:decimal">
            <xs:pattern value="[0-9]+"/>
        </xs:restriction>
    </xs:simpleType>
    
         
</xs:schema>

=== RichardVinueza/U.T.4---Actividad-6---Proyecto-de-Github-con-Readme.md./tourism/public_html/ecuador.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<country xmlns="https://www.richard.com/tourism"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://www.richard.com/tourism country.xsd">
    <beaches>
        <beach>
            <top>1</top>
            <name>Playa Los Frailes</name>
            <location>Manabi</location>   
        </beach>
        <beach>
            <top>2</top>
            <name>Playa de Canoa</name>
            <location>Manabi</location>  
        </beach>
        <beach>
            <top>3</top>
            <name>Playa de Atacames</name>
            <location>Esmeraldas</location>
        </beach>   
    </beaches>
    <hotels>
        <hotel>
            <name>Nu House Boutique Hotel</name>
            <place>Quito</place>
            <price>100</price>
        </hotel>
        <hotel>
            <name>Hotel Continental</name>
            <place>Guayaquil</place>
            <price>131</price>
        </hotel>
        
        <hotel>
            <name>Hotel El Dorado</name>
            <place>Cuenca</place>
            <price>90</price>
        </hotel> 
    </hotels>
</country>

=== RichardVinueza/U.T.4---Actividad-6---Proyecto-de-Github-con-Readme.md./tourism/public_html/spain.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<country xmlns="https://www.richard.com/tourism"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://www.richard.com/tourism country.xsd">
    <beaches>
        <beach>
            <top>1</top>
            <name>Macarella</name>
            <location>Balearic Islands</location>   
        </beach>
        <beach>
            <top>2</top>
            <name>Playa de Benijo</name>
            <location>Canary Islands</location>  
        </beach>
        <beach>
            <top>3</top>
            <name>Playa los Genoveses</name>
            <location>Andalucia</location>
        </beach>   
    </beaches>
    <hotels>
        <hotel>
            <name>Hotel Alfonso XIII</name>
            <place>Sevilla</place>
            <price>2000</price>
        </hotel>
        <hotel>
            <name>Finca Cortesin</name>
            <place>Malaga</place>
            <price>700</price>
        </hotel>
        
        <hotel>
            <name>El Palace</name>
            <place>Barcelona</place>
            <price>1000</price>
        </hotel> 
    </hotels>
</country>
